version: "3.9"

services:
    backend:
        build: ./backend
        container_name: biyuyo-backend
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - biyuyo-network

    frontend:
        build: ./frontend
        container_name: biyuyo-frontend
        volumes:
            - ./frontend:/app
        ports:
            - "3000:80"
        networks:
            - biyuyo-network

    db:
        image: postgres:18.3
        container_name: biyuyo-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - biyuyo-network

networks:
    biyuyo-network:
        driver: bridge

volumes:
    db_data:
