[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
command=gunicorn app.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 120
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=
    DJANGO_SETTINGS_MODULE="app.settings",
    SECRET_KEY="%(ENV_SECRET_KEY)s",
    DEBUG="%(ENV_DEBUG)s",
    DB_NAME="%(ENV_DB_NAME)s",
    DB_USER="%(ENV_DB_USER)s",
    DB_PASSWORD="%(ENV_DB_PASSWORD)s",
    DB_HOST="%(ENV_DB_HOST)s",
    DB_PORT="%(ENV_DB_PORT)s",
    DJANGO_ALLOWED_HOSTS="%(ENV_DJANGO_ALLOWED_HOSTS)s",
    CORS_ALLOWED_ORIGINS="%(ENV_CORS_ALLOWED_ORIGINS)s"
