# Generated by Django 6.0.3 on 2026-06-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_updated_at'),
        ('sales', '0002_alter_payment_updated_at_alter_sale_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
