# Generated by Django 6.0.3 on 2026-06-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_updated_at'),
        ('suppliers', '0002_add_status_to_purchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('business_id', 'supplier_id'), name='unique_purchase_per_supplier'),
        ),
    ]
