# Generated by Django 6.0.3 on 2026-06-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_purchase_unique_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase_per_supplier',
        ),
    ]
